version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: "echo 'db.stats()' | mongosh --host localhost:27017 --authenticationDatabase admin -u root -p example || exit 1"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  webapp:
    build: .
    container_name: dotnet-mongo-crud
    ports:
      - "8080:5035"  # Maps port 5035 in the container to port 8080 on the host
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDB__ConnectionString: "mongodb://root:example@mongodb:27017"
      MongoDB__DatabaseName: "ProductDB"
    volumes:
      - ./appsettings.json:/app/appsettings.json

volumes:
  mongo-data:

